name = "hello-world"
main = "src/index.js"
compatibility_date = "2024-04-03"

[vars]
SITE_TITLE = "Hello World"
DEFAULT_GREETING = "Hello World"

# Deploying without --env will use the built-in greeting with no D1 binding.

[env.d1]
name = "hello-world-d1"

[[env.d1.d1_databases]]
binding = "HELLO_WORLD_DB"
database_name = "hello_world"
# Replace this placeholder (or run `npm run db:ensure`) after creating the database
# with `wrangler d1 create hello_world`.
database_id = "00000000-0000-0000-0000-000000000000"

[env.preview]
name = "hello-world-preview"

[[env.preview.d1_databases]]
binding = "HELLO_WORLD_DB"
database_name = "hello_world"
# This can match the production database id once created
# or you can leave it blank for local development.
database_id = ""
