# This template config is safe to modify locally. The CI workflow rewrites it during deployment.
name = "hello-world-cf-worker-d1"
main = "src/index.js"
compatibility_date = "2024-11-18"

[vars]
SITE_TITLE = "Hello World"
SITE_RELEASE = "v1.0.0"

[[d1_databases]]
binding = "HELLO_WORLD_DB"
database_name = "hello_world"
database_id = "00000000-0000-0000-0000-000000000000"
