name: Apply D1 id to wrangler.toml

on:
  workflow_dispatch:

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fetch the D1 database id
        run: npm run db:github-env -- --github-env=CF_D1_DATABASE_ID
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Apply the id to wrangler.toml
        run: npm run db:apply-env -- --env=CF_D1_DATABASE_ID
