name: Deploy to Cloudflare Worker with D1

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Or your project's Node version

      - name: Install dependencies
        run: |
          npm install wrangler --save-dev
          sudo apt update && sudo apt install -y jq  # For JSON parsing

      - name: Create or get D1 database and bind
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # Set database name (change as needed)
          DB_NAME="hello-world"
          BINDING_NAME="DB"  # The env variable name in your Worker code (e.g., env.DB)

          # Authenticate Wrangler (uses CF_API_TOKEN env var automatically)
          npx wrangler whoami

          # List existing D1 databases
          DBS=$(npx wrangler d1 list --json)

          # Check if DB exists and get ID
          DB_ID=$(echo "$DBS" | jq -r --arg name "$DB_NAME" '.[] | select(.name == $name) | .id')

          if [ -z "$DB_ID" ]; then
            # Create if not exists
            CREATE_OUTPUT=$(npx wrangler d1 create $DB_NAME --json)
            DB_ID=$(echo "$CREATE_OUTPUT" | jq -r '.uuid')  # Note: Output uses 'uuid' for ID
            echo "Created new D1 database with ID: $DB_ID"
          else
            echo "Using existing D1 database with ID: $DB_ID"
          fi

          # Check if binding already exists in wrangler.toml to avoid duplicates
          if ! grep -q "database_id = \"$DB_ID\"" wrangler.toml; then
            # Append D1 binding to wrangler.toml
            echo "" >> wrangler.toml  # Newline for safety
            echo "[[d1_databases]]" >> wrangler.toml
            echo "binding = \"$BINDING_NAME\"" >> wrangler.toml
            echo "database_name = \"$DB_NAME\"" >> wrangler.toml
            echo "database_id = \"$DB_ID\"" >> wrangler.toml
            echo "D1 binding added/updated in wrangler.toml"
          else
            echo "D1 binding already present in wrangler.toml"
          fi

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}